* * *

Matrices
--------

A matrix is a two dimensional data set with columns and rows.

A column is a vertical representation of data, while a row is a horizontal representation of data.

A matrix can be created with the `matrix()` function. Specify the `nrow` and `ncol` parameters to get the amount of rows and columns:

### Example

```r
# Create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2)

# Print the matrix
thismatrix
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices)

**Note:** Remember the `c()` function is used to concatenate items together.



In [ ]:
# Create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2)

# Print the matrix
thismatrix

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

You can also create a matrix with strings:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices2)

* * *





In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

Access Matrix Items
-------------------

You can access the items by using `[ ]` brackets. The first number "1" in the bracket specifies the row-position, while the second number "2" specifies the column-position:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[1, 2]
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_access)



In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[1, 2]

[1] "cherry"

The whole row can be accessed if you specify a comma **after** the number in the bracket:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[2,]
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_access_row)



In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[2,]

[1] "banana" "orange"

The whole column can be accessed if you specify a comma **before** the number in the bracket:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[,2]
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_access_col)

* * *



In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix[,2]

[1] "cherry" "orange"


Access More Than One Row
------------------------

More than one row can be accessed if you use the `c()` function:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[c(1,2),]
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_access_row2)

* * *



In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[c(1,2),]

[,1]   [,2]   [,3] 
[1,] apple  orange pear 
[2,] banana grape  melon

Access More Than One Column
---------------------------

More than one column can be accessed if you use the `c()` function:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[, c(1,2)]
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_access_col2)

* * *



In [5]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix[, c(1,2)]

[,1]   [,2]     
[1,] apple  orange   
[2,] banana grape    
[3,] cherry pineapple

Add Rows and Columns
--------------------

Use the `cbind()` function to add additional columns in a Matrix:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- cbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_add_cols)

**Note:** The cells in the new column must be of the same length as the existing matrix.



In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- cbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

[,1]   [,2]      [,3]  [,4]      
[1,] apple  orange    pear  strawberry
[2,] banana grape     melon blueberry 
[3,] cherry pineapple fig   raspberry

Use the `rbind()` function to add additional rows in a Matrix:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- rbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_add_rows)

**Note:** The cells in the new row must be of the same length as the existing matrix.

* * *



In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- rbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

[,1]       [,2]      [,3]     
[1,] apple      orange    pear     
[2,] banana     grape     melon    
[3,] cherry     pineapple fig      
[4,] strawberry blueberry raspberry

Remove Rows and Columns
-----------------------

Use the `c()` function to remove rows and columns in a Matrix:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)

#Remove the first row and the first column
thismatrix <- thismatrix[-c(1), -c(1)]

thismatrix
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_remove_rows_cols)

* * *



In [1]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)

#Remove the first row and the first column
thismatrix <- thismatrix[-c(1), -c(1)]

thismatrix

[1] "mango"     "pineapple"

Check if an Item Exists
-----------------------

To find out if a specified item is present in a matrix, use the `%in%` operator:

### Example

Check if "apple" is present in the matrix:

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

"apple" %in% thismatrix
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_check)

* * *



In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

"apple" %in% thismatrix

[1] TRUE

Number of Rows and Columns
--------------------------

Use the `dim()` function to find the number of rows and columns in a Matrix:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

dim(thismatrix)
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_dim)

* * *



In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

dim(thismatrix)

[1] 2 2

Matrix Length
-------------

Use the `length()` function to find the dimension of a Matrix:

### Example

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

length(thismatrix)
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_length)

Total cells in the matrix is the number of rows multiplied by number of columns.

In the example above: Dimension = 2\*2 = **4**.

* * *



In [ ]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

length(thismatrix)

[1] 4

Loop Through a Matrix
---------------------

You can loop through a Matrix using a `for` loop. The loop will start at the first row, moving right:

### Example

Loop through the matrix items and print them:

```r
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_loop)

* * *



In [ ]:
# Create a 2x2 matrix called "thismatrix" with specified values
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

# Loop through each row
for (rows in 1:nrow(thismatrix)) {
  # Loop through each column
  for (columns in 1:ncol(thismatrix)) {
    # Print the value at the current row and column
    print(thismatrix[rows, columns])
  }
}


[1] "apple"
[1] "cherry"
[1] "banana"
[1] "orange"


Combine two Matrices
--------------------

Again, you can use the `rbind()` or `cbind()` function to combine two or more matrices together:

### Example

```r
# Create two 2x2 matrices: Matrix1 and Matrix2
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)

# Combine matrices as rows using rbind
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined
```

1. **Matrix Creation**:
   - We create two matrices:
     - `Matrix1` with the elements: "apple", "banana", "cherry", and "grape".
     - `Matrix2` with the elements: "orange", "mango", "pineapple", and "watermelon".

2. **Combining as Rows (Using `rbind`)**:
   - The `rbind` function stacks matrices vertically (row-wise).
   - When we apply `rbind(Matrix1, Matrix2)`, the resulting matrix (`Matrix_Combined`) will have the rows from `Matrix1` followed by the rows from `Matrix2`.
   - The output of `Matrix_Combined` will be:
     ```
     apple       banana
     cherry      grape
     orange      mango
     pineapple   watermelon
     ```

3. **Combining as Columns (Using `cbind`)**:
   - Next, we combine the matrices as columns using `cbind`:
     ```R
     Matrix_Combined <- cbind(Matrix1, Matrix2)
     Matrix_Combined
     ```
   - The resulting matrix (`Matrix_Combined`) will have the columns from `Matrix1` followed by the columns from `Matrix2`.
   - The output of `Matrix_Combined` will be:
     ```
     apple       banana      orange       mango
     cherry      grape       pineapple    watermelon
     ```

In summary, `rbind` stacks matrices vertically, while `cbind` joins them horizontally. You can choose the appropriate method based on your specific requirements! 🍎🍌🍊🍍

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_matrices_combine)

In [ ]:
# Create two 2x2 matrices: Matrix1 and Matrix2
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)

# Combine matrices as rows using rbind
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined


## Exercises for Absolute Beginners on R Matrices:

**Exercise 1: Accessing Matrix Elements (Easy)**

1. Create a 3x3 matrix called `fruit_basket` with the following elements:
    - Row 1: "apple", "banana", "orange"
    - Row 2: "grape", "pineapple", "mango"
    - Row 3: "strawberry", "watermelon", "kiwi"
2. Print the element in the second row and first column of `fruit_basket`.
3. Print the entire second row of `fruit_basket`.
4. Print the entire third column of `fruit_basket`.

**Instructions:**

* Use the code provided in the example for accessing matrix elements using `[ ]` brackets.
* Remember to specify the row and column number within the brackets.
* For printing entire rows or columns, use commas within the brackets.

**Challenge:** Try modifying the exercise to access different elements based on user input (e.g., ask the user for a row and column number and print the corresponding element).

**Exercise 2: Adding Rows and Columns (Easy)**

1. Create a 2x2 matrix called `shopping_list` with the following elements:
    - Row 1: "milk", "bread"
    - Row 2: "eggs", "cheese"
2. Add a new column to `shopping_list` with the elements "butter" and "yogurt".
3. Add a new row to `shopping_list` with the elements "apples" and "bananas".
4. Print the updated `shopping_list` matrix.

**Instructions:**

* Use the `cbind()` function to add new columns, specifying the elements as a separate vector.
* Use the `rbind()` function to add new rows, specifying the elements as a separate vector.
* Ensure the dimensions of the new elements match the existing matrix.

**Challenge:** Extend the exercise by allowing the user to specify the items they want to add to the shopping list.

**Exercise 3: Combining and Checking Matrices (Medium)**

1. Create two 2x2 matrices: `fruit1` with elements "apple", "banana", "mango", "grape" and `fruit2` with elements "orange", "pineapple", "watermelon", "kiwi".
2. Combine `fruit1` and `fruit2` into a single matrix by:
    - Stacking them vertically using `rbind()`.
    - Joining them horizontally using `cbind()`.
3. Check if the element "apple" exists in both `fruit1` and `fruit2` using the `%in%` operator.
4. Calculate the total number of elements in both matrices combined.

**Instructions:**

* Use the `rbind()` and `cbind()` functions as demonstrated in the provided code.
* Use the `%in%` operator to compare elements between matrices.
* Remember that the length of a matrix represents the total number of elements.

**Challenge:** Modify the exercise to compare more complex conditions between elements (e.g., check if elements start with a specific letter or belong to a particular category).

Remember to provide detailed instructions and comments within the code snippets to guide absolute beginners through these exercises. You can also adapt the difficulty level or add more exercises based on your learner's needs and progress.

Absolutely! Here are the exercises with solutions and explanatory comments:

**Exercise 1: Accessing Matrix Elements (Super Easy)**

```r
# Create a 3x3 matrix named "fruit_basket" with specific elements
fruit_basket <- matrix(c("apple", "banana", "orange", "grape", "pineapple", "mango", "strawberry", "watermelon", "kiwi"), nrow = 3, ncol = 3)

# Print the element at row 2, column 1
print(fruit_basket[2, 1])   # Output: grape

# Print the entire second row
print(fruit_basket[2, ])    # Output: grape pineapple mango

# Print the entire third column
print(fruit_basket[, 3])    # Output: orange mango kiwi

# Challenge: Access based on user input
row_num <- as.integer(readline(prompt = "Enter row number (1-3): "))
col_num <- as.integer(readline(prompt = "Enter column number (1-3): "))
print(fruit_basket[row_num, col_num])
```

**Explanation:**

* We use `matrix()` to create the `fruit_basket` matrix with specified elements and dimensions.
* To access an element, we use `[ ]` brackets, specifying the row and column number within.
* Commas within brackets select entire rows or columns.
* The challenge demonstrates how to adapt the code for user input باستخدام `readline()`.

**Exercise 2: Adding Rows and Columns (Easy)**

```r
# Create a 2x2 matrix named "shopping_list" with specific elements
shopping_list <- matrix(c("milk", "bread", "eggs", "cheese"), nrow = 2, ncol = 2)

# Add a new column with "butter" and "yogurt"
new_items <- c("butter", "yogurt")
shopping_list <- cbind(shopping_list, new_items)

# Add a new row with "apples" and "bananas"
new_row <- c("apples", "bananas")
shopping_list <- rbind(shopping_list, new_row)

# Print the updated shopping list
print(shopping_list)
```

**Explanation:**

* We create the `shopping_list` matrix and define the new items for the column and row.
* `cbind()` adds elements as a new column, ensuring dimensions match existing rows.
* `rbind()` adds elements as a new row, ensuring dimensions match existing columns.
* The final `print()` shows the updated shopping list.

**Challenge:** You can modify the code to prompt the user for items using `readline()` and integrate them into `cbind()` and `rbind()`.

**Exercise 3: Combining and Checking Matrices (Medium)**

```r
# Create two 2x2 matrices named "fruit1" and "fruit2" with specific elements
fruit1 <- matrix(c("apple", "banana", "mango", "grape"), nrow = 2, ncol = 2)
fruit2 <- matrix(c("orange", "pineapple", "watermelon", "kiwi"), nrow = 2, ncol = 2)

# Combine matrices vertically using rbind()
combined_fruits_vertical <- rbind(fruit1, fruit2)

# Combine matrices horizontally using cbind()
combined_fruits_horizontal <- cbind(fruit1, fruit2)

# Check if "apple" exists in both matrices
is_apple_in_both <- "apple" %in% c(fruit1, fruit2)

# Calculate total number of elements
total_elements <- nrow(combined_fruits_vertical) * ncol(combined_fruits_vertical)

# Print results
print(combined_fruits_vertical)
print(combined_fruits_horizontal)
print(is_apple_in_both)
print(total_elements)
```

**Explanation:**

* We create the `fruit1` and `fruit2` matrices with specified elements.
* `rbind()` combines them vertically, stacking rows on top of each other.
* `cbind()` combines them horizontally, placing columns side-by-side.
* `%in%` checks if "apple" exists in both matrices combined (as a single vector).
* `nrow()` and `ncol()` determine the number of rows and columns, respectively.
* The final `print()` statements display the combined matrices, the existence check result, and the total element count.

**Challenge:** You can modify the code to compare more complex conditions between elements using operators like `>`, `<`, or regular expressions. You can also explore different matrix manipulation techniques