#R Arrays
* * *

Arrays
------

Compared to matrices, arrays can have more than two dimensions.

We can use the `array()` function to create an array, and the `dim` parameter to specify the dimensions:

#### Example Explained

In the example below we create an array with the values 1 to 24.

How does `dim=c(4,3,2)` work?  
The first and second number in the bracket specifies the amount of rows and columns.  
The last number in the bracket specifies how many dimensions we want.

**Note:** Arrays can only have one data type.

* * *
### Example

```R
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)
thisarray

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray
```
[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_array)

1. **Creating a One-Dimensional Array (`thisarray`)**:
   - We create a one-dimensional array called `thisarray`.
   - The values in this array range from **1 to 24**.
   - The syntax `c(1:24)` generates a sequence of numbers from 1 to 24.
   - The resulting `thisarray` contains the following elements:
     ```
     [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
     ```

2. **Creating a Multi-Dimensional Array (`multiarray`)**:
   - We create a multi-dimensional array using the `array` function.
   - The `dim` argument specifies the dimensions of the array.
   - In this case, we set the dimensions to **4 rows, 3 columns, and 2 "layers"**.
   - The values from `thisarray` are filled into the multi-dimensional structure.
   - The resulting `multiarray` has the following structure:
     ```
     , , 1

          [,1] [,2] [,3]
     [1,]    1    5    9
     [2,]    2    6   10
     [3,]    3    7   11
     [4,]    4    8   12

     , , 2

          [,1] [,2] [,3]
     [1,]   13   17   21
     [2,]   14   18   22
     [3,]   15   19   23
     [4,]   16   20   24
     ```
   - Each "layer" corresponds to a different set of values from `thisarray`.

In summary, we've created both a one-dimensional array and a multi-dimensional array in R! 📊🔍


In [ ]:
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)
thisarray

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))
# Print the multiarray with row and column labels
print(multiarray, quote = FALSE)

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24



In [ ]:
# Default behaviour of showing multiarray in Google Colab
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)
thisarray

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray #the results amay appear on different versions of R. below is teh default behaviour in Google Colab

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

In [ ]:
R.version


Access Array Items
------------------

You can access the array elements by referring to the index position. You can use the `[]` brackets to access the desired elements from an array:

The syntax is as follow: `array[row position, column position, matrix level]`

### Example

```r
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Access the value at row 2, column 3, and layer 2
multiarray[2, 3, 2]
```

1. **Creating a One-Dimensional Array (`thisarray`)**:
   - We create a one-dimensional array called `thisarray`.
   - The values in this array range from **1 to 24**.
   - The syntax `c(1:24)` generates a sequence of numbers from 1 to 24.

2. **Creating a Multi-Dimensional Array (`multiarray`)**:
   - We create a multi-dimensional array using the `array` function.
   - The `dim` argument specifies the dimensions of the array.
   - In this case, we set the dimensions to **4 rows, 3 columns, and 2 "layers"**.
   - The values from `thisarray` are filled into the multi-dimensional structure.

3. **Accessing a Specific Value**:
   - The expression `multiarray[2, 3, 2]` retrieves the value at:
     - Row 2
     - Column 3
     - Layer 2
   - In this case, the value is **10** (which corresponds to the position of the number 10 in `thisarray`).

So, `multiarray[2, 3, 2]` gives us the value at the specified position within the multi-dimensional array. 📊🔍

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_array_access)




In [ ]:
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Access the value at row 2, column 3, and layer 2
multiarray[2, 3, 2]


You can also access the whole row or column from a matrix in an array, by using the `c()` function:

### Example

A comma (,) before c() means that we want to access the column.

A comma (,) after c() means that we want to access the row.


```r
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Access all the items from the first row of the first matrix
multiarray[c(1),,1]

# Access all the items from the first column of the first matrix
multiarray[,c(1),1]
```

1. **Creating a One-Dimensional Array (`thisarray`)**:
   - We create a one-dimensional array called `thisarray`.
   - The values in this array range from **1 to 24**.

2. **Creating a Multi-Dimensional Array (`multiarray`)**:
   - We create a multi-dimensional array using the `array` function.
   - The `dim` argument specifies the dimensions of the array.
   - In this case, we set the dimensions to **4 rows, 3 columns, and 2 "layers"**.
   - The values from `thisarray` are filled into the multi-dimensional structure.

3. **Accessing Items from the First Row and First Column**:
   - `multiarray[c(1),,1]` retrieves all the items from the first row of the first matrix.
   - `multiarray[,c(1),1]` retrieves all the items from the first column of the first matrix.

We've created a multi-dimensional array and accessed specific rows and columns within it! 📊🔍

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_array_access_rc)

* * *



In [ ]:
#A comma (,) before c() means that we want to access the column.
#A comma (,) after c() means that we want to access the row.

# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Access all the items from the first row of the first matrix
multiarray[c(1),,1]

# Access all the items from the first column of the first matrix
multiarray[,c(1),1]

[1] 1 5 9

[1] 1 2 3 4

* * *

Check if an Item Exists
-----------------------

To find out if a specified item is present in an array, use the `%in%` operator:

### Example

Check if the value "2" is present in the array:

```r
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Check if the value 2 exists in the entire multiarray
2 %in% multiarray
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_array_check)

* * *


In [ ]:
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Check if the value 2 exists in the entire multiarray
2 %in% multiarray


[1] TRUE


Amount of Rows and Columns
--------------------------

Use the `dim()` function to find the amount of rows and columns in an array:

### Example

```r
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Get the dimensions of the multiarray
dim(multiarray)
```


[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_array_dim)

* * *



In [ ]:
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Get the dimensions of the multiarray
dim(multiarray)


[1] 4 3 2

Array Length
------------

Use the `length()` function to find the dimension of an array:

### Example

```r
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Get the total number of elements in the multiarray
length(multiarray)
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_array_length)

* * *



In [ ]:
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Get the total number of elements in the multiarray
length(multiarray)


[1] 24

Loop Through an Array
---------------------

You can loop through the array items by using a `for` loop:

### Example

```r
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Loop through each element in the multiarray
for(x in multiarray){
  # Print the current element
  print(x)
}
```

[Try it Yourself »](https://www.w3schools.com/r/tryr.asp?filename=demo_array_loop)

In [ ]:
# Create a one-dimensional array called "thisarray" with values from 1 to 24
thisarray <- c(1:24)

# Create a multi-dimensional array called "multiarray"
# with dimensions 4 rows, 3 columns, and 2 "layers"
multiarray <- array(thisarray, dim = c(4, 3, 2))

# Loop through each element in the multiarray
for(x in multiarray){
  # Print the current element
  print(x)
}


[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24
